site_name: Design Docs for aasx-core
nav:
    - Home: index.md
    - General Design Decisions: general-design-decisions.md
    - Simplified Python: simplified-python.md
    - Data Structures and Operations: data-structures-and-operations.md
    - Code Contracts: contracts.md
    - De/serialization Scripts: deserialization-scripts.md
    - Testing: testing.md
    - Naming Conventions: naming-conventions.md
    - Roadmap: roadmap.md
theme: readthedocs
markdown_extensions:
    - toc:
        permalink: "#"
